### ISSUE TITLE
Why do you need to retransmit the token when you restart the bot? Isn’t it possible to save it somewhere?

### ISSUE THREAD

**Issue by VecH** [usememos/telegram-integration#16]
Why do you need to retransmit the token when you restart the bot? Isn’t it possible to save it somewhere?

**Comment by boojack** [comment]
It's an enhancement and already in the roadmap. https://github.com/usememos/telegram-integration/blob/main/memogram.go#L25 

And due to our limited development resources, contribution is always welcome.

**Comment by VecH** [comment]
Unfortunately, I haven’t been programming for more than 10 years; I haven’t encountered the GO language
