### ISSUE TITLE
memogram日志报错

### ISSUE THREAD

**Issue by brmysss** [usememos/telegram-integration#22]
<img width="1512" alt="image" src="https://github.com/usememos/telegram-integration/assets/41810235/5b12bd07-e867-4bd6-83d2-6f5822fa108b">
<img width="1512" alt="image" src="https://github.com/usememos/telegram-integration/assets/41810235/c0dae3e8-854e-468c-97bc-945eda90df6a">
这个问题该如何解决？

memos版本：v0.22.2

**Comment by ootvt** [comment]
@brmysss 你好，你解决了吗，我也遇到这个问题了

**Comment by brmysss** [comment]
> @brmysss 你好，你解决了吗，我也遇到这个问题了

已经解决了

**Comment by kabuda001** [comment]
> > @brmysss 你好，你解决了吗，我也遇到这个问题了
> 
> 已经解决了

大佬，如何解决的，我加了代理之后，直接启动失败，报错为：
connection error: desc = \"error reading server preface: read tcp 192.168.10.6:35780->192.168.10.100:7890: read: connection reset by peer\""

**Comment by brmysss** [comment]
> > > @brmysss 你好，你解决了吗，我也遇到这个问题了
> > 
> > 
> > 已经解决了
> 
> 大佬，如何解决的，我加了代理之后，直接启动失败，报错为： connection error: desc = "error reading server preface: read tcp 192.168.10.6:35780->192.168.10.100:7890: read: connection reset by peer""

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/7f4265c9-e003-4dc9-a9bb-8828310eaf05">
