### ISSUE TITLE
telegram bot转发内容问题反馈

### ISSUE THREAD

**Issue by brmysss** [usememos/telegram-integration#23]
转发内容给telegram bot，单条内容里如果有多张图片，程序会把每一种图片都当成一张memos去处理。

这一点在v0.21版本是不会出现的。
<img width="1122" alt="image" src="https://github.com/usememos/telegram-integration/assets/41810235/c6dbeead-478e-4132-ae57-06fcd617f73a">

但是在v0.22.1版本会将每一张图片都生成一张memos
<img width="1123" alt="image" src="https://github.com/usememos/telegram-integration/assets/41810235/fb79afea-8de1-4fbb-9871-a1f47d5f939d">

该版本还存在一个问题：
tg里的内容如果是超链接，如「点击直达」，转发给telegrambot同步到memos后就变成了纯文本格式了，链接就消失了。

**Comment by aliuq** [comment]
I have the same problem. When I forward multiple photos in a message, it is divided into a single memo instead of a whole. Similarly, if there is a hyperlink in the content, the link disappears.

**Comment by dwong33** [comment]
Yes I have the same problem for that, whenever I include multiple photos as attachment to a single telegram message, it will eventually create a memo for each of the photos.

**Comment by dwong33** [comment]
Any insight on this issue? I have been a bug for about 2 months...

**Comment by dwong33** [comment]
Anyone is still encounter this problem? This problem persists on my machine. How come it is closed?
