### ISSUE TITLE
功能建议，保存笔记后可以设置笔记权限

### ISSUE THREAD

**Issue by monlor** [usememos/telegram-integration#27]
之前的tg机器人在保存笔记后可以设置笔记权限，现在不行了
<img width="363" alt="image" src="https://github.com/usememos/telegram-integration/assets/20394007/235538cc-9a3a-490a-95d0-670896caf41b">

**Comment by le0zh0u** [comment]
想问下，这个项目你是部署在外网吗

**Comment by Asakushen** [comment]
> 想问下，这个项目你是部署在外网吗

网络需要能访问tg

**Comment by le0zh0u** [comment]
> > 想问下，这个项目你是部署在外网吗
> 
> 网络需要能访问tg

那意味着memos也部署在可以访问tg的服务器上？
我之前尝试了将这个项目部署在国外机器上，但是不知道怎么连接到国内的跑着memos的服务器，想请教一下~
