### ISSUE TITLE
Was it necessary?

### ISSUE THREAD

**Issue by weikib** [usememos/telegram-integration#40]
You know that moment when you're using an app and they add features that break the functionality? 

Today I will talk about my use case, having natively . 

Telegram bot on one side, memos on the other, the bot added to a telegram group, being able to forward there messages, photos, audios etc and upload them to memos. 

Having telegram, natively, with my id added to my user profile and without having to worry about anything else, being able to put the user, I had never experienced a single problem in my intensive use of the bot, not a single complaint about its operation in months of use.

The day comes when, in the name of insurmountable problems that I had never experienced, it is decided to mutilate the application by removing the native option, by a generator of frustration and headache (aka "memogram").

The app is fantastic and that's why I decided to support it as a sponsor, but the new telegram integration, for my use case, sucks. 

I hope the rest of the community has benefited from this change, as far as I'm concerned, it was a step backwards. It was losing the functionality of telegram. 

Good luck!

**Comment by boojack** [comment]
@weikib Memos is an open-source project with all its code publicly available. It still has many issues, both enhancements and bugs. Good maintainability is essential for the project's healthy development, so third-party integration code should be in a separate project. Separating the Telegram integration makes it easier to maintain and add new features. This change benefits both our maintenance work and community contributions.

If you have any issues with the Telegram integration, please create an issue and await updates or community contributions.

**Comment by okainov** [comment]
I'm absolutely new user and I started to use memos actually today. Seems like it's working fine, there are indeed some improvements which can be done, but I'm really confused with this issue. What is actually wrong here?

**Comment by dwong33** [comment]
> I'm absolutely new user and I started to use memos actually today. Seems like it's working fine, there are indeed some improvements which can be done, but I'm really confused with this issue. What is actually wrong here?

Welcome to memos and honestly, it is a good tool for personal journaling.

I have been using it for a year, and you will find some features being added and removed from time to time. And often some features once being configurable in the web interface now require some configurations on the docker config which adds complexity. The Telegram integration was once a contributor supported plug-in and later developer decided to integrate it into the main app. And it is now being detached to another plugin.

I am not a developer, I am not familiar with the code structure, but as a layman user, I found it somehow weird as I don't find many other projects add and remove and add features like this. But I am happy that finally boojack replied why telegram integration has to be an independent project, and I respect his decision.

Finally, the current Telegram plug in will create separate memos for each photo, which is not the desired outcome. This bug issue was opened on Jun 13 and it has been two months and seems that no one is looking into the issue.

**Comment by weikib** [comment]
Good afternoon, 

Although the change with respect to telegram, was a negative change for usability for the end user, it is understandable the point of avoiding having third party apis lurking around the application. From a programmer's point of view it can be understood. 

The change was traumatic to stop being able to send different images at once or the impossibility of having a solid solution. If for example you restart the container or in different casuisticas... you must reconfigure the bot. 

That was my complaint. 

The developer's explanation is totally valid.


Beyond this inconvenience, memos is in my top5 of self-hosted applications, I consider it essential in my daily life, as well as another project of the same developer. 

Therefore, I invite anyone who uses memos regularly, to donate to the project, not memos, but any open source project. 



About memos, it is in my top 10 applications and probably, @ as a developer of this kind of apps, it would be in the top 5 for the other project it has. Clean, precise, chiro work.

Recently memos has added the option to view “Created on...” and “Updated on...” a feature the app needed almost from day one. 

To anyone reading this who uses the app frequently, sponsor.


Sponsor, go to the developer's profile and click sponsor. 


In a one-man orchestra, we can't demand more, but we can contribute.
