### ISSUE TITLE
Memos will create separate memos for each photo in a Telegram message rather than multiple photos in one memo

### ISSUE THREAD

**Issue by dwong33** [usememos/telegram-integration#49]
The content of this bug is the same as this one, but that issue is closed:

https://github.com/usememos/telegram-integration/issues/23

But the bug is not being addressed as of v0.22.4.

Previously, we can include multiple photos in a memos by using Telegram bot. But currently, if we attempt to create a memos with more than one photo, memos will create each photo a memo, which is not the expected outcome.

**Comment by okainov** [comment]
This sounds as trivial as replacing accessing last picture in `if` to `for`-loop here: https://github.com/usememos/telegram-integration/blob/main/memogram.go#L174

**Comment by boojack** [comment]
@okainov It's actually an arrry of `PhotoSize`, so this's not what we need.
* https://github.com/go-telegram/bot/blob/main/models/message.go#L103
* https://github.com/go-telegram/bot/blob/main/models/photo_size.go#L4

**Comment by okainov** [comment]
Just looking at it, it still looks exactly what we need :) Each PhotoSize has FileID (which we use), so just iterate over it...

**Comment by boojack** [comment]
@okainov The problem now is that it will be saved as multiple memos instead of just one memo with the last image in it. 

And the photosize is all available size of the image with same file id. Not what you thought.
