### ISSUE TITLE
Unable to Integrate Memogram with Telegram

### ISSUE THREAD

**Issue by erbanku** [usememos/telegram-integration#75]
I'm encountering an issue when trying to integrate Memogram with Telegram. The application fails to start due to a permission error related to accessing a file. Below is the error log:

```
root@aws:~$ docker logs memogram
panic: failed to init store: failed to load user access token map from file: open data.txt: permission denied

goroutine 1 [running]:
main.main()
        /app/bin/memogram/main.go:13 +0x45
panic: failed to init store: failed to load user access token map from file: open data.txt: permission denied

goroutine 1 [running]:
main.main()
        /app/bin/memogram/main.go:13 +0x45
```

<details>
<summary>Details</summary>

![image](https://github.com/user-attachments/assets/3d1cf7ec-e3de-4d39-8308-2250314160af)

</details>

**Comment by erbanku** [comment]
Poor documentation and support.

**Comment by wensley** [comment]
same

**Comment by alcir** [comment]
If you add `COPY data.txt data.txt ` to the Dockerfile, it works.
```
...
COPY .env.example .env
COPY data.txt data.txt 
COPY --from=builder /app/memogram .
CMD ["./memogram"]
```
BTW I don't know what `data.txt` is supposed to contain :-)

**Comment by wayanjimmy** [comment]
@alcir  you can put the access token in data.txt so the bot will not asking every restart
